name: 'Rename UPM Package'
author: 'PhantasmicDev'
description: 'Renames and edits files to reflect a name change in package.'
branding:
  icon: 'edit-3'
  color: 'gray-dark'
  
inputs:
  company-name:
    required: true
  package-name:
    required: true
  package-root-path:
    default: '.'
  full-name:
  domain-extension:
    default: 'com'

runs:
  using: "composite"
  steps:
    - name: Gather Names
      run: |
        ASMDEF_BASE_NAME=$(echo "${{ inputs.company-name }}"."${{ inputs.package-name }}" | sed 's/ //g')
        echo "runtime-asmdef-name="$ASMDEF_BASE_NAME"" >> $GITHUB_ENV
        echo "editor-asmdef-name="$ASMDEF_BASE_NAME".Editor" >> $GITHUB_ENV
        echo "runtime-tests-asmdef-name="$ASMDEF_BASE_NAME".Tests" >> $GITHUB_ENV
        echo "editor-tests-asmdef-name="$ASMDEF_BASE_NAME".Editor.Tests" >> $GITHUB_ENV
        echo "package-json-path="${{ inputs.package-root-path }}"/package.json
        
        if [ -n "${{ inputs.full-name }}" ]; then
          echo "full-name="${{ inputs.full-name }}"" >> $GITHUB_ENV
        else
          FULL_NAME=$(echo "${{ inputs.domain-extension }}"."$ASMDEF_BASE_NAME" | tr '[:upper:]' '[:lower:]' | sed -r 's/[^-_\.]//g')
          echo "full-name="$FULL_NAME"" >> $GITHUB_ENV
          echo "full package name was not provided so generated name '$FULL_NAME' will be used"
        fi
      shell: bash
      
    - name: Update package.json
      run: echo $(jq ".name =| "${{ env.full-name }}" | .displayName =| "${{ inputs.package-name }}"" "${{ env.package-json-path }}") > "${{ env.package-json-path }}"
      shell: bash
      
    - name: Rename Assembly Definition Files
      run: |
        function rename_asmdef() {
          local ASMDEF=$1
          local NEW_NAME=$2
          
          if [ -n "$ASMDEF" ]; then
            RENAMED_ASMDEF=$(dirname "$ASMDEF")/"$NEW_NAME".asmdef
            mv "$ASMDEF" "$RENAMED_ASMDEF"
            
            if [ -n "$ASMDEF".meta ]; then
              mv "$ASMDEF".meta "$RENAMED_ASMDEF".meta
            else
              echo "Notice: No '.meta' file for "$ASMDEF" was found to rename." >&2
            fi
            
            echo "$RENAMED_ASMDEF"
        }
        
        RUNTIME_ASMDEF=$(find "${{ inputs.package-root-path }}"/Runtime -name "*.asmdef" -type f -quit)
        if [ -n "$RUNTIME_ASMDEF" ]; then
          echo "runtime-asmdef=$(rename_asmdef "$RUNTIME_ASMDEF" "${{ env.runtime-asmdef-name }}") >> $GITHUB_ENV
        else
          echo 'Notice: No Runtime assembly definition file was found.'
        fi
        
        EDITOR_ASMDEF=$(find "${{ inputs.package-root-path }}"/Editor -name "*.asmdef" -type f -quit)
        if [ -n "$EDITOR_ASMDEF" ]; then
          echo "editor-asmdef=$(rename_asmdef "$EDITOR_ASMDEF" "${{ env.editor-asmdef-name }}") >> $GITHUB_ENV
        else
          echo 'Notice: No Editor assembly definition file was found.'
        fi
        
        RUNTIME_TESTS_ASMDEF=$(find "${{ inputs.package-root-path }}"/Tests/Runtime -name "*.asmdef" -type f -quit)
        if [ -n "$RUNTIME_TESTS_ASMDEF" ]; then
          echo "runtime-tests-asmdef=$(rename_asmdef "$RUNTIME_TESTS_ASMDEF" "${{ env.runtime-tests-asmdef-name }}") >> $GITHUB_ENV
        else
          echo 'Notice: No Runtime Tests assembly definition file was found.'
        fi
        
        EDITOR_TESTS_ASMDEF=$find "${{ inputs.package-root-path }}"/Tests/Editor -name "*.asmdef" -type f -quit)
        if [ -n "$EDITOR_TESTS_ASMDEF" ]; then
          echo "editor-tests-asmdef=$(rename_asmdef "$EDITOR_TESTS_ASMDEF" "${{ env.editor-tests-asmdef-name }}") >> $GITHUB_ENV
        else
          echo 'Notice: No Editor Tests assembly definition file was found.'
        fi
      shell: bash
      
      - name: Update Assembly Definition Files
        run: |
          declare -A OLD_TO_NEW_REFERENCES
          
          function update_asmdef() {
            local ASMDEF_FILE=$1
            local ASMDEF_NAME=$2
            
            OLD_TO_NEW_REFERENCES["$(jq '.name' "$ASMDEF_FILE")"]="$ASMDEF_NAME"
            
            echo $(jq '.name |= "$ASMDEF_NAME"' "$ASMDEF_FILE") > "$ASMDEF_FILE"
            echo "Updated name entry of "$ASMDEF_FILE" to "$ASMDEF_NAME""
            
            function update_references() {
              local OLD_REFERENCE=$1
              local NEW_REFERENCE=$2
              
              jq -c '.references | to_entries[]' "$ASMDEF_FILE" | while read -r entry; do
                index=$(echo $entry | jq '.key')
                value=$(echo $entry | jq -r '.value')
                if [ "$value" == "$OLD_REFERENCE" ]; then
                  echo $(jq ".references[$index] |= \"$NEW_REFERENCE"\"" "$ASMDEF_FILE") > "$ASMDEF_FILE"
                  break
                fi
              done
            }
                        
            for OLD_REFERENCE in "${!OLD_TO_NEW_REFERENCES[@]}"; do
              NEW_REFERENCE=${OLD_TO_NEW_REFERENCES[$key]}
              update_references $OLD_REFERENCE $NEW_REFERENCE
            done
          }
          
          if [ -n "${{ env.runtime-asmdef }}" ]; then
            update_asmdef "${{ env.runtime-asmdef }}" "${{ env.runtime-asmdef-name }}"
          fi
          
          if [ -n "${{ env.editor-asmdef }}" ]; then
            update_asmdef "${{ env.editor-asmdef }}" "${{ env.editor-asmdef-name }}"
          fi
          
          if [ -n "${{ env.runtime-tests-asmdef }}" ]; then
            update_asmdef "${{ env.runtime-tests-asmdef }} "${{ env.runtime-tests-asmdef-name }}"
          fi
          
          if [ -n "${{ env.runtime-tests-asmdef }}" ]; then
            update_asmdef "${{ env.editor-tests-asmdef }} "${{ env.editor-tests-asmdef-name }}"
          fi
        shell: bash
