name: Rename Test

on:
  workflow_dispatch:

jobs:
  Rename:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rename Package
        uses: PhantasmicDev/rename-upm-package@main
        with:
          company-name: "Kool Kompany"
          package-name: "Kool Pakege"
          package-root-path: "Test/My Test Package"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "Test/My Test Package"
