name: Rename Test

on:
  workflow_dispatch:
    inputs:
      company-name:
        description: Company Name
        type: string
        required: true
      package-name:
        description: Package Name
        type: string
        required: true

permissions:
  contents: write

jobs:
  Rename:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rename Package
        uses: PhantasmicDev/rename-upm-package@main
        with:
          company-name: "${{ inputs.company-name }}"
          package-name: "${{ inputs.package-name }}"
          package-root-path: "My-Test-Package"

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Renamed Package
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
